-- Generated from generator/demo_specs/aws-vietnam-renewable-solar.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-renewable-solar
-- This is the schema that is actually deployed for VIETNAM_RENEWABLE_SOLAR.

-- Alerts fire on the bottom tail of Solar Generation
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_SOLAR_GENERATION) AS T
  FROM RAW.GENERATION_READINGS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_SOLAR_GENERATION <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_SOLAR_GENERATION), 2) AS AVG_SOLAR_GENERATION,
  ROUND(AVG(f.KPI_CURTAILMENT), 2) AS AVG_CURTAILMENT,
  ROUND(AVG(f.KPI_TOMORROW_FORECAST), 2) AS AVG_TOMORROW_FORECAST,
  ROUND(AVG(f.KPI_IRRADIANCE_INDEX), 2) AS AVG_IRRADIANCE_INDEX,
  ROUND(AVG(f.KPI_DEGRADATION_RATE), 2) AS AVG_DEGRADATION_RATE
FROM RAW.GENERATION_READINGS f
JOIN RAW.SOLAR_SITES e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_SOLAR_GENERATION), 2) AS AVG_SOLAR_GENERATION,
  ROUND(AVG(f.KPI_CURTAILMENT), 2) AS AVG_CURTAILMENT,
  ROUND(AVG(f.KPI_TOMORROW_FORECAST), 2) AS AVG_TOMORROW_FORECAST,
  ROUND(AVG(f.KPI_IRRADIANCE_INDEX), 2) AS AVG_IRRADIANCE_INDEX,
  ROUND(AVG(f.KPI_DEGRADATION_RATE), 2) AS AVG_DEGRADATION_RATE
FROM RAW.GENERATION_READINGS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_SOLAR_GENERATION) AS KPI_SOLAR_GENERATION, AVG(KPI_CURTAILMENT) AS KPI_CURTAILMENT, AVG(KPI_TOMORROW_FORECAST) AS KPI_TOMORROW_FORECAST, AVG(KPI_IRRADIANCE_INDEX) AS KPI_IRRADIANCE_INDEX, AVG(KPI_DEGRADATION_RATE) AS KPI_DEGRADATION_RATE FROM RAW.GENERATION_READINGS),
     en AS (SELECT SUM(KPI_CAPACITY_FACTOR) AS KPI_CAPACITY_FACTOR, SUM(KPI_PLANTS_ACTIVE) AS KPI_PLANTS_ACTIVE FROM RAW.SOLAR_SITES)
  SELECT 1 AS SORT_ORDER, 'Solar Generation' AS TITLE, KPI_SOLAR_GENERATION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SOLAR_GENERATION)) AS DECIMAL(38,0))) || ' ' || 'GWh' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Capacity Factor' AS TITLE, KPI_CAPACITY_FACTOR AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CAPACITY_FACTOR), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Curtailment' AS TITLE, KPI_CURTAILMENT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CURTAILMENT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Plants Active' AS TITLE, KPI_PLANTS_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PLANTS_ACTIVE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Tomorrow Forecast' AS TITLE, KPI_TOMORROW_FORECAST AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TOMORROW_FORECAST), 1) AS DECIMAL(38,1))) || ' ' || 'GWh' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Irradiance Index' AS TITLE, KPI_IRRADIANCE_INDEX AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_IRRADIANCE_INDEX), 1) AS DECIMAL(38,1))) || ' ' || 'kWh/m²' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Degradation Rate' AS TITLE, KPI_DEGRADATION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DEGRADATION_RATE), 1) AS DECIMAL(38,1))) || '%/yr' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
