-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Solar Farm Analytics
-- ============================================================================
USE DATABASE SOLAR_ANALYTICS;
USE SCHEMA ML;

-- ML.FORECAST: SOLAR_ANALYTICS_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.SOLAR_ANALYTICS_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FORECAST_INPUT'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.SOLAR_ANALYTICS_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.SOLAR_ANALYTICS_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: SOLAR_ANALYTICS_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.SOLAR_ANALYTICS_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.SOLAR_ANALYTICS_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.SOLAR_ANALYTICS_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'), SERIES_COLNAME => 'ENTITY_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

