-- ============================================================================
-- 99_RESET.SQL — Reset Solar Farm Analytics to clean demo state
-- ============================================================================
USE DATABASE SOLAR_ANALYTICS;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST SUSPEND;
ALTER TASK IF EXISTS APP.TASK_DETECT SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.PERFORMANCE_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYTICS REFRESH;
ALTER DYNAMIC TABLE CURATED.FORECAST_INPUT REFRESH;
ALTER DYNAMIC TABLE CURATED.OPERATIONAL_RISK REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM SOLAR_ANALYTICS.RAW.OPERATIONS → 100000
-- SELECT COUNT(*) FROM SOLAR_ANALYTICS.RAW.METRICS → 500000
-- SELECT COUNT(*) FROM SOLAR_ANALYTICS.ML.SOLAR_ANALYTICS_FORECAST_RESULTS → >0

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST RESUME;
ALTER TASK IF EXISTS APP.TASK_DETECT RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST RESUME;
